### ISSUE TITLE
Stylize Back to Professors button on Results Page

### ISSUE THREAD

**Issue by talhathmd** [acmuta/mavgrades#6]
app/results/page.tsx
```typescript
<button 
  onClick={() => {
    setSelectedProfessor(null);
    setSelectedYear(null);
    setSelectedSemester(null);
  }} 
  className="mt-4 text-blue-500 underline"
  >
  Back to Professors
  </button>
``` 
This is where the button should be at
![image](https://github.com/user-attachments/assets/88a5d879-ed1b-40a9-a05b-fdf954531541)

**Comment by kevinrouz** [comment]
Merged: [ecd82f5](https://github.com/acmuta/uta-grades/commit/ecd82f5d66920da50bdd5faa6f555d5a326d32b7)
